### ISSUE TITLE
Improve Logging across codebase

### ISSUE THREAD

**Issue by p0lygun** [battlefield-portal-community/bfportal.gg#177]
Currently, because we use gunicorn in production, django logs are hidden. this should not happen as it makes debugging for errors in prod very hard.

So to resolve that we need to have a better logging setup.

### Subtasks
- [ ] Make Django logs show up in stdout and stderr 
- [ ] Increase gunicorn logging level
- [ ] Use the same logging format for Django and gunicorn
- [ ] Log more data and functions in the database
