### ISSUE TITLE
TODO pre-launch

### ISSUE THREAD

**Issue by p0lygun** [battlefield-portal-community/bfportal.gg#78]
- [x] #80
- [x] #81
- [x]  new state for exp code button when they're copied
- [x] #82
- [x] #83
- [x] #84
- [x] #85
- [x] "official Battlefield exp" page should lead to a  "coming soon" page
- [x] Remove test tags and add the ones for current production env
- [x] Test and add OGP and Twitter link preview for all pages
- [x] #87
- [x] Update DB
- [x] Do a final test of whole website

**Comment by p0lygun** [comment]
the website is now published at http://bfportal.gg
