### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by p0lygun** [battlefield-portal-community/bfportal.gg#79]
### In progress

- [x] #93
- [x] #90
- [ ]  On /admin > update theme with mata code sent on discord
- [ ]  add patreon link
- [ ]  Share button

---

## Todo

**UI / QoL features**  

- [ ] Report button on experience page should get darker when hovered (like header menu text)
- [ ] Report button should have less space at the right (same margin as heart)
- [ ] Experience description text content size should stop a bit sooner (more space on the right so the report button don't overlap on most screens)
- [ ]  Autocomplete on experience name / experience creator name in the filters
- [ ]  Expand sort by like count box so it don't overlap with the chevron (arrow) icon
- [ ]  Add a text link "PSD Template" in the exp submit page after cover image URL title (like description)
- [ ]  On /admin > update theme with mata code sent on discord
- [ ] Add just a bit of spacing between column one and column two of page buttons
- [ ]  add patreon link
- [ ]  Share button
- [ ]  Create an official BF account > Turn on official bf page + icon before exp name
- [ ]  New burger menu items UI 
 
**Big features**  

- [ ] add exp reporting backend
- [ ] XP Indicator +tag
- [ ] Add "variants" and "more from creator" section in experience page
- [ ] Add a LIVE server browser in bfportal.gg using gametools API. But only for experiences submitted on bfportal.gg.
Flow : open exp page > click on "host exp server" button > check if experience is live with API > show server info
(MATA NEED TO DO AN UI CONCEPT)
This feature would be linked to the bfportal.gg bot and send a message to a specific channel.
- [ ] Show number of server / player playing the experience somewhere on the card using API (prob won't be possible as Arcur said)
- [ ] JSON Logic storage and recovery when sharing experience url

--- 

### Done
- [x]  Change heart icon in the "made with <3..." banner with the same as the like icon.
- [x] Add just a bit of spacing between column one and column two of page buttons
- [x]  Align pages button to the cards (on the left) and pages buttons **text** (on the right)

**Comment by Matavatar** [comment]
**UI / QoL features**
- [ ] Autocomplete on experience name / experience creator name in the filters
- [ ] Expand sort by like count box so it don't overlap with the chevron (arrow) icon
- [ ] Add a text link "PSD Template" in the exp submit page after cover image URL title (like description)
- [ ] On /admin > change purple to our dark grey color + change bird icon to our logo
- [ ] Change heart icon in the "made with <3..." banner with the same as the like icon.
- [ ] Align pages button to the cards (on the left) and pages buttons **text** (on the right)
- [ ] Add just a bit of spacing between column one and column two of page buttons

**Big features**
- [ ] Add a LIVE server browser in bfportal.gg using gametools API. But only for experiences submitted on bfportal.gg.
Flow : open exp page > click on "host exp server" button > check if experience is live with API > show server info
(MATA NEED TO DO AN UI CONCEPT)
This feature would be linked to the bfportal.gg bot and send a message to a specific channel.

**Comment by p0lygun** [comment]
@Matavatar need some clarification on 
>  Align pages button to the cards (on the left) and pages buttons text (on the right)

**Comment by Matavatar** [comment]
>  On /admin > change purple to our dark grey color + change bird icon to our logo

![image](https://user-images.githubusercontent.com/65628145/193475068-7cc8c147-f2c2-4b71-8279-b83812569617.png)

**Comment by Matavatar** [comment]
- [ ] when non logged user click on like > go to login page

**Comment by Matavatar** [comment]
- [ ] Cool badges for users profile page

**Comment by Matavatar** [comment]
- [ ] add patreon link

**Comment by Matavatar** [comment]
- [ ] add image of an experience as a link preview and home page banner as home preview

**Comment by p0lygun** [comment]
do #70
